apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  labels:
    app: fortio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
---
apiVersion: v1
kind: Service
metadata:
  name: fortio
spec:
  ports:
  - port: 80
    targetPort: http-fortio
  selector:
    app: fortio 