apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-agent
  labels:
    app: k8s-agent
spec:
  selector:
    matchLabels:
      app: k8s-agent
  template:
    metadata:
      labels:
        app: k8s-agent
    spec:
      terminationGracePeriodSeconds: 6
      serviceAccountName: k8s-agent
      containers:
        - name: k8s-agent
          image: potatospudowski/k8s-agent:1.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/coreweave-load-balancer-type: public
  name: k8s-agent
spec:
  type: LoadBalancer
  selector:
    app: k8s-agent
  ports:
    - port: 80
      targetPort: 3000